<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegistrationsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('registrations')->insert([
            [
                'room_no' => 200,
                'seater' => 2,
                'fees_per_month' => 910,
                'total_amount' => 10920,
                'stay_from' => '2021-03-07',
                'duration' => 12,
                'course' => 'Bachelors In Information Technology',
                'reg_no' => '11101',
                'first_name' => 'Mary',
                'middle_name' => 'A.',
                'last_name' => 'Martin',
                'gender' => 'female',
                'contact_no' => '7455558855',
                'email_id' => 'marym@mail.com',
                'emergency_contact_no' => '7412589650',
                'guardian_name' => 'James Martin',
                'guardian_relation' => 'Father',
                'guardian_contact_no' => '7896666600',
                'correspondence_address' => '20 Patterson Street',
                'correspondence_city' => 'Houston',
                'correspondence_state' => '',
                'correspondence_pincode' => 70067,
                'permanent_address' => '20 Patterson Street',
                'permanent_city' => 'Houston',
                'permanent_state' => '',
                'permanent_pincode' => 70067,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_no' => 112,
                'seater' => 3,
                'fees_per_month' => 1300,
                'total_amount' => 15600,
                'stay_from' => '2022-04-04',
                'duration' => 12,
                'course' => 'Master of Computer Application',
                'reg_no' => 'CA003',
                'first_name' => 'Richard',
                'middle_name' => 'J.',
                'last_name' => 'Summers',
                'gender' => 'Male',
                'contact_no' => '1325658800',
                'email_id' => 'richards@mail.com',
                'emergency_contact_no' => '4785555500',
                'guardian_name' => 'Maren Summers',
                'guardian_relation' => 'Father',
                'guardian_contact_no' => '4125478555',
                'correspondence_address' => '48 Wilkinson Street',
                'correspondence_city' => 'Nashville',
                'correspondence_state' => '',
                'correspondence_pincode' => 32701,
                'permanent_address' => '48 Wilkinson Street',
                'permanent_city' => 'Nashville',
                'permanent_state' => '',
                'permanent_pincode' => 32701,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_no' => 132,
                'seater' => 5,
                'fees_per_month' => 1990,
                'total_amount' => 11940,
                'stay_from' => '2022-04-04',
                'duration' => 6,
                'course' => 'Master In Business Administration',
                'reg_no' => 'CA006',
                'first_name' => 'Jennifer',
                'middle_name' => 'J.',
                'last_name' => 'Frye',
                'gender' => 'Female',
                'contact_no' => '7895555544',
                'email_id' => 'jennifer@mail.com',
                'emergency_contact_no' => '2224445585',
                'guardian_name' => 'Beverly Frye',
                'guardian_relation' => 'Mother',
                'guardian_contact_no' => '1478569888',
                'correspondence_address' => '18 Hanifan Lane',
                'correspondence_city' => 'Stone Mountain',
                'correspondence_state' => '',
                'correspondence_pincode' => 38803,
                'permanent_address' => '18 Hanifan Lane',
                'permanent_city' => 'Stone Mountain',
                'permanent_state' => '',
                'permanent_pincode' => 38803,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_no' => 269,
                'seater' => 2,
                'fees_per_month' => 910,
                'total_amount' => 10920,
                'stay_from' => '2022-05-03',
                'duration' => 12,
                'course' => 'Bachelor of Engineering',
                'reg_no' => 'CA002',
                'first_name' => 'Bruce',
                'middle_name' => 'E.',
                'last_name' => 'Murphy',
                'gender' => 'Male',
                'contact_no' => '1346565650',
                'email_id' => 'bruce@mail.com',
                'emergency_contact_no' => '7850001450',
                'guardian_name' => 'Ellen Murphy',
                'guardian_relation' => 'Mother',
                'guardian_contact_no' => '7850001010',
                'correspondence_address' => '25 Yorkie Lane',
                'correspondence_city' => 'Savannah',
                'correspondence_state' => '',
                'correspondence_pincode' => 34001,
                'permanent_address' => '25 Yorkie Lane',
                'permanent_city' => 'Savannah',
                'permanent_state' => '',
                'permanent_pincode' => 34001,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_no' => 100,
                'seater' => 5,
                'fees_per_month' => 1990,
                'total_amount' => 15920,
                'stay_from' => '2022-04-17',
                'duration' => 8,
                'course' => 'Bachelor Of Commerce',
                'reg_no' => 'CA009',
                'first_name' => 'Nancy',
                'middle_name' => 'W.',
                'last_name' => 'Vasquez',
                'gender' => 'Female',
                'contact_no' => '3547777770',
                'email_id' => 'nancy@mail.com',
                'emergency_contact_no' => '4445554470',
                'guardian_name' => 'Jude Vasquez',
                'guardian_relation' => 'Father',
                'guardian_contact_no' => '4785698555',
                'correspondence_address' => '109 Prudence Street',
                'correspondence_city' => 'Dearborn',
                'correspondence_state' => '',
                'correspondence_pincode' => 44550,
                'permanent_address' => '109 Prudence Street',
                'permanent_city' => 'Dearborn',
                'permanent_state' => '',
                'permanent_pincode' => 44550,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_no' => 310,
                'seater' => 1,
                'fees_per_month' => 750,
                'total_amount' => 9000,
                'stay_from' => '2022-04-10',
                'duration' => 12,
                'course' => 'Master of Information Technology',
                'reg_no' => 'CA014',
                'first_name' => 'Liam',
                'middle_name' => 'K.',
                'last_name' => 'Moore',
                'gender' => 'Male',
                'contact_no' => '7854441014',
                'email_id' => 'liamoore@mail.com',
                'emergency_contact_no' => '7412585500',
                'guardian_name' => 'Christine L. Moore',
                'guardian_relation' => 'Mother',
                'guardian_contact_no' => '7458888888',
                'correspondence_address' => '77 Test Address',
                'correspondence_city' => 'Democity',
                'correspondence_state' => '',
                'correspondence_pincode' => 70001,
                'permanent_address' => '77 Test Address',
                'permanent_city' => 'Democity',
                'permanent_state' => '',
                'permanent_pincode' => 70001,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
